defmodule Radiator.Repo.Migrations.Personas do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:transcripts, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :text, :text, null: false
      add :start_time_ms, :bigint, null: false
      add :end_time_ms, :bigint, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :track_id, :uuid
    end

    create table(:tracks, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:transcripts) do
      modify :track_id,
             references(:tracks,
               column: :id,
               name: "transcripts_track_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:tracks) do
      add :name, :text, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :episode_id,
          references(:episodes,
            column: :id,
            name: "tracks_episode_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :episode_persona_id, :uuid, null: false
    end

    create table(:roles, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create table(:personas, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :public_name, :text, null: false
      add :handle, :text, null: false
      add :description, :text
      add :avatar_png, :binary
      add :default?, :boolean
      add :person_id, :uuid
    end

    create table(:people, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:personas) do
      modify :person_id,
             references(:people,
               column: :id,
               name: "personas_person_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    create unique_index(:personas, [:handle], name: "personas_handle_index")

    alter table(:people) do
      add :real_name, :text, null: false
      add :nickname, :text
      add :email, :text
      add :telephone, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create table(:episode_personas, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:tracks) do
      modify :episode_persona_id,
             references(:episode_personas,
               column: :id,
               name: "tracks_episode_persona_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:episode_personas) do
      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :episode_id,
          references(:episodes,
            column: :id,
            name: "episode_personas_episode_id_fkey",
            type: :uuid,
            prefix: "public"
          ), null: false

      add :persona_id,
          references(:personas,
            column: :id,
            name: "episode_personas_persona_id_fkey",
            type: :uuid,
            prefix: "public"
          ), null: false

      add :role_id,
          references(:roles,
            column: :id,
            name: "episode_personas_role_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    create unique_index(:episode_personas, [:episode_id, :persona_id],
             name: "episode_personas_one_persona_per_episode_index"
           )
  end

  def down do
    drop_if_exists unique_index(:episode_personas, [:episode_id, :persona_id],
                     name: "episode_personas_one_persona_per_episode_index"
                   )

    drop constraint(:episode_personas, "episode_personas_episode_id_fkey")

    drop constraint(:episode_personas, "episode_personas_persona_id_fkey")

    drop constraint(:episode_personas, "episode_personas_role_id_fkey")

    alter table(:episode_personas) do
      remove :role_id
      remove :persona_id
      remove :episode_id
      remove :updated_at
      remove :inserted_at
    end

    drop constraint(:tracks, "tracks_episode_persona_id_fkey")

    alter table(:tracks) do
      modify :episode_persona_id, :uuid
    end

    drop table(:episode_personas)

    alter table(:people) do
      remove :updated_at
      remove :inserted_at
      remove :telephone
      remove :email
      remove :nickname
      remove :real_name
    end

    drop_if_exists unique_index(:personas, [:handle], name: "personas_handle_index")

    drop constraint(:personas, "personas_person_id_fkey")

    alter table(:personas) do
      modify :person_id, :uuid
    end

    drop table(:people)

    drop table(:personas)

    drop table(:roles)

    drop constraint(:tracks, "tracks_episode_id_fkey")

    alter table(:tracks) do
      remove :episode_persona_id
      remove :episode_id
      remove :updated_at
      remove :inserted_at
      remove :name
    end

    drop constraint(:transcripts, "transcripts_track_id_fkey")

    alter table(:transcripts) do
      modify :track_id, :uuid
    end

    drop table(:tracks)

    drop table(:transcripts)
  end
end
