defmodule Radiator.Repo.Migrations.AddIdentityForEpisodeNumberAndShowId do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create unique_index(:episodes, [:number, :show_id], name: "episodes_number_index")
  end

  def down do
    drop_if_exists unique_index(:episodes, [:number, :show_id], name: "episodes_number_index")
  end
end
