defmodule Radiator.Repo.Migrations.FixMnemonicTypo do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    rename table(:shows), :nmemonic, to: :mnemonic
  end

  def down do
    rename table(:shows), :mnemonic, to: :nmemonic
  end
end
