defmodule Radiator.Repo.Migrations.RenameDonationToFunding do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    rename table(:shows), :donation_url, to: :funding_url

    rename table(:shows), :donation_description, to: :funding_description
  end

  def down do
    rename table(:shows), :funding_description, to: :donation_description

    rename table(:shows), :funding_url, to: :donation_url
  end
end
