defmodule Radiator.Repo.Migrations.ChangeShowsItunesTypeDefaultToEpisodicAndForbidNil do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:shows) do
      modify :itunes_type, :text, null: false, default: "episodic"
    end
  end

  def down do
    alter table(:shows) do
      modify :itunes_type, :text, null: true, default: "serial"
    end
  end
end
