defmodule Radiator.Repo.Migrations.AddUniqueSchedulingPerEpisode do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create unique_index(:chapters, [:episode_id], name: "chapters_unique_episode_index")
  end

  def down do
    drop_if_exists unique_index(:chapters, [:episode_id], name: "chapters_unique_episode_index")
  end
end
