defmodule Radiator.Repo.Migrations.StoreEpisodeDurationInMilliseconds do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    rename table(:episodes), :duration_seconds, to: :duration_ms
  end

  def down do
    rename table(:episodes), :duration_ms, to: :duration_seconds
  end
end
