defmodule Radiator.Repo.Migrations.AddGuidToShows do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:shows) do
      add :guid, :uuid, null: false
    end
  end

  def down do
    alter table(:shows) do
      remove :guid
    end
  end
end
