defmodule Radiator.Repo.Migrations.RenameShowsSqlTable do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:podcasts, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :guid, :text, null: false, default: fragment("gen_random_uuid()")
      add :title, :text, null: false
      add :subtitle, :text
      add :summary, :text
      add :mnemonic, :text
      add :language, :text
      add :itunes_type, :text, null: false, default: "episodic"
      add :license_name, :text
      add :license_url, :text
      add :author, :text
      add :itunes_category, {:array, :text}, null: false, default: []
      add :blocked, :boolean, null: false, default: false
      add :explicit, :boolean, null: false, default: false
      add :complete, :boolean, null: false, default: false
      add :funding_url, :text
      add :funding_description, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :license_id,
          references(:licenses,
            column: :id,
            name: "podcasts_license_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    drop constraint(:episodes, "episodes_podcast_id_fkey")

    alter table(:episodes) do
      modify :podcast_id,
             references(:podcasts,
               column: :id,
               name: "episodes_podcast_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )
    end
  end

  def down do
    drop constraint(:episodes, "episodes_podcast_id_fkey")

    alter table(:episodes) do
      modify :podcast_id,
             references(:shows,
               column: :id,
               name: "episodes_podcast_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )
    end

    drop constraint(:podcasts, "podcasts_license_id_fkey")

    drop table(:podcasts)
  end
end
