defmodule Radiator.Repo.Migrations.AddEpisodeToShowsRelationship do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:episodes) do
      add :show_id,
          references(:shows,
            column: :id,
            name: "episodes_show_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end
  end

  def down do
    drop constraint(:episodes, "episodes_show_id_fkey")

    alter table(:episodes) do
      remove :show_id
    end
  end
end
