defmodule Radiator.Repo.Migrations.AllowNilForEpisodeNumber do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:episodes) do
      modify :number, :bigint, null: true
    end
  end

  def down do
    alter table(:episodes) do
      modify :number, :bigint, null: false
    end
  end
end
