defmodule Radiator.Repo.Migrations.RenameShowToPodcast do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop constraint(:episodes, "episodes_show_id_fkey")

    drop_if_exists unique_index(:episodes, [:number, :show_id], name: "episodes_number_index")

    rename table(:episodes), :show_id, to: :podcast_id

    alter table(:episodes) do
      modify :podcast_id,
             references(:shows,
               column: :id,
               name: "episodes_podcast_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )
    end

    create unique_index(:episodes, [:number, :podcast_id], name: "episodes_number_index")
  end

  def down do
    drop_if_exists unique_index(:episodes, [:number, :podcast_id], name: "episodes_number_index")

    drop constraint(:episodes, "episodes_podcast_id_fkey")

    alter table(:episodes) do
      modify :podcast_id,
             references(:shows,
               column: :id,
               name: "episodes_show_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )
    end

    rename table(:episodes), :podcast_id, to: :show_id

    create unique_index(:episodes, [:number, :show_id], name: "episodes_number_index")
  end
end
