defmodule Radiator.Repo.Migrations.ChangeGuidToString do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:shows) do
      modify :guid, :text
    end

    alter table(:episodes) do
      modify :guid, :text
    end
  end

  def down do
    alter table(:episodes) do
      modify :guid, :uuid
    end

    alter table(:shows) do
      modify :guid, :uuid
    end
  end
end
