defmodule Radiator.Repo.Migrations.SchedulingForEpisodes do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:chapters) do
      modify :episode_id, :uuid, null: true
      modify :title, :text, null: true
      modify :start_time_ms, :bigint, null: true
      add :proposals, :map
    end
  end

  def down do
    alter table(:chapters) do
      remove :proposals
      modify :start_time_ms, :bigint, null: false
      modify :title, :text, null: false
      modify :episode_id, :uuid, null: false
    end
  end
end
