defmodule Radiator.Repo.Migrations.AddDefaultGuidGenerateFunctionToShowsAndEpisodes do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:shows) do
      modify :guid, :uuid, default: fragment("gen_random_uuid()")
    end

    alter table(:episodes) do
      modify :guid, :uuid, default: fragment("gen_random_uuid()")
    end
  end

  def down do
    alter table(:episodes) do
      modify :guid, :uuid, default: nil
    end

    alter table(:shows) do
      modify :guid, :uuid, default: nil
    end
  end
end
