defmodule Radiator.Repo.Migrations.StoreChapterStartTimeInMilliseconds do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop_if_exists unique_index(:chapters, [:start_time_seconds, :episode_id],
                     name: "chapters_start_time_index"
                   )

    rename table(:chapters), :start_time_seconds, to: :start_time_ms

    create unique_index(:chapters, [:start_time_ms, :episode_id],
             name: "chapters_start_time_index"
           )
  end

  def down do
    drop_if_exists unique_index(:chapters, [:start_time_ms, :episode_id],
                     name: "chapters_start_time_index"
                   )

    rename table(:chapters), :start_time_ms, to: :start_time_seconds

    create unique_index(:chapters, [:start_time_seconds, :episode_id],
             name: "chapters_start_time_index"
           )
  end
end
