defmodule Radiator.Repo.Migrations.DropSchedulingParticipantUserIds do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:episode_scheduling) do
      remove :participant_user_ids
    end
  end

  def down do
    alter table(:episode_scheduling) do
      add :participant_user_ids, {:array, :uuid}, null: false, default: []
    end
  end
end
