defmodule Radiator.Repo.Migrations.AddPodcastFieldsFromFeed do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:episode_contributors, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :role, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :episode_id,
          references(:episodes,
            column: :id,
            name: "episode_contributors_episode_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false

      add :person_id, :uuid, null: false
    end

    alter table(:episodes) do
      add :guid, :text
      add :season, :bigint
      add :episode_type, :text
      add :subtitle, :text
      add :summary, :text
      add :content_html, :text
      add :author, :text
      add :link, :text
      add :published_at, :utc_datetime_usec
      add :duration_seconds, :bigint
      add :image_url, :text
      add :enclosure_url, :text
      add :enclosure_length, :bigint
      add :enclosure_type, :text
      add :chapters, {:array, :map}, default: []
      add :chapters_url, :text
      add :chapters_type, :text
      add :transcripts, {:array, :map}, default: []
      add :last_seen_in_feed_at, :utc_datetime_usec
    end

    create unique_index(:episodes, [:podcast_id, :guid],
             name: "episodes_unique_guid_per_podcast_index"
           )

    create table(:persons, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:episode_contributors) do
      modify :person_id,
             references(:persons,
               column: :id,
               name: "episode_contributors_person_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )
    end

    create index(:episode_contributors, [:episode_id])

    create index(:episode_contributors, [:person_id])

    alter table(:persons) do
      add :name, :text, null: false
      add :normalized_name, :text, null: false
      add :uri, :text
      add :image_url, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :user_id,
          references(:users,
            column: :id,
            name: "persons_user_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false
    end

    create unique_index(:persons, [:user_id, :normalized_name],
             name: "persons_unique_name_per_user_index"
           )

    create index(:persons, [:user_id])

    alter table(:podcasts) do
      add :subtitle, :text
      add :summary, :text
      add :description, :text
      add :link, :text
      add :language, :text
      add :author, :text
      add :owner_name, :text
      add :owner_email, :text
      add :image_url, :text
      add :copyright, :text
      add :license, :text
      add :license_url, :text
      add :funding_url, :text
      add :funding_text, :text
      add :podcast_type, :text
      add :explicit, :boolean
      add :feed_guid, :text
      add :categories, {:array, :map}, default: []
      add :sync_strategy, :text, null: false, default: "manual"
      add :sync_status, :text, null: false, default: "idle"
      add :last_checked_at, :utc_datetime_usec
      add :last_imported_at, :utc_datetime_usec
      add :last_sync_error, :text
      add :http_etag, :text
      add :http_last_modified, :text
    end
  end

  def down do
    alter table(:podcasts) do
      remove :http_last_modified
      remove :http_etag
      remove :last_sync_error
      remove :last_imported_at
      remove :last_checked_at
      remove :sync_status
      remove :sync_strategy
      remove :categories
      remove :feed_guid
      remove :explicit
      remove :podcast_type
      remove :funding_text
      remove :funding_url
      remove :license_url
      remove :license
      remove :copyright
      remove :image_url
      remove :owner_email
      remove :owner_name
      remove :author
      remove :language
      remove :link
      remove :description
      remove :summary
      remove :subtitle
    end

    drop_if_exists index(:persons, [:user_id])

    drop constraint(:persons, "persons_user_id_fkey")

    drop_if_exists unique_index(:persons, [:user_id, :normalized_name],
                     name: "persons_unique_name_per_user_index"
                   )

    alter table(:persons) do
      remove :user_id
      remove :updated_at
      remove :inserted_at
      remove :image_url
      remove :uri
      remove :normalized_name
      remove :name
    end

    drop_if_exists index(:episode_contributors, [:person_id])

    drop_if_exists index(:episode_contributors, [:episode_id])

    drop constraint(:episode_contributors, "episode_contributors_person_id_fkey")

    drop constraint(:episode_contributors, "episode_contributors_episode_id_fkey")

    alter table(:episode_contributors) do
      modify :person_id, :uuid
    end

    drop table(:persons)

    drop_if_exists unique_index(:episodes, [:podcast_id, :guid],
                     name: "episodes_unique_guid_per_podcast_index"
                   )

    alter table(:episodes) do
      remove :last_seen_in_feed_at
      remove :transcripts
      remove :chapters_type
      remove :chapters_url
      remove :chapters
      remove :enclosure_type
      remove :enclosure_length
      remove :enclosure_url
      remove :image_url
      remove :duration_seconds
      remove :published_at
      remove :link
      remove :author
      remove :content_html
      remove :summary
      remove :subtitle
      remove :episode_type
      remove :season
      remove :guid
    end

    drop table(:episode_contributors)
  end
end
