defmodule Radiator.Repo.Migrations.CreateEpisodes do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:episodes, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :title, :text, null: false
      add :number, :bigint

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :podcast_id,
          references(:podcasts,
            column: :id,
            name: "episodes_podcast_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false
    end

    create index(:episodes, [:podcast_id])
  end

  def down do
    drop_if_exists index(:episodes, [:podcast_id])

    drop constraint(:episodes, "episodes_podcast_id_fkey")

    drop table(:episodes)
  end
end
