defmodule Radiator.Repo.Migrations.AddOwnerPersonaFkToScheduling do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:episode_scheduling) do
      modify :owner_persona_id,
             references(:personas,
               column: :id,
               name: "episode_scheduling_owner_persona_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :restrict
             )
    end

    create index(:episode_scheduling, [:owner_persona_id])
  end

  def down do
    drop_if_exists index(:episode_scheduling, [:owner_persona_id])

    drop constraint(:episode_scheduling, "episode_scheduling_owner_persona_id_fkey")

    alter table(:episode_scheduling) do
      modify :owner_persona_id, :uuid
    end
  end
end
