defmodule Radiator.Repo.Migrations.AddSchedulingFields do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop constraint(:episode_scheduling, "episode_scheduling_episode_id_fkey")

    execute "ALTER TABLE episode_scheduling ALTER COLUMN proposals TYPE jsonb[] USING CASE WHEN proposals IS NULL THEN ARRAY[]::jsonb[] ELSE ARRAY[proposals] END"
    execute "ALTER TABLE episode_scheduling ALTER COLUMN proposals SET NOT NULL"
    execute "ALTER TABLE episode_scheduling ALTER COLUMN proposals SET DEFAULT ARRAY[]::jsonb[]"

    alter table(:episode_scheduling) do
      add :status, :text, null: false, default: "open"
      add :owner_persona_id, :uuid, null: false
      add :participant_persona_ids, {:array, :uuid}, null: false, default: []
      add :chosen_proposal_id, :uuid
      add :chosen_datetime, :utc_datetime
      add :published_at, :utc_datetime
      add :finalized_at, :utc_datetime

      modify :episode_id,
             references(:episodes,
               column: :id,
               name: "episode_scheduling_episode_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             ),
             null: false
    end
  end

  def down do
    drop constraint(:episode_scheduling, "episode_scheduling_episode_id_fkey")

    alter table(:episode_scheduling) do
      modify :episode_id,
             references(:episodes,
               column: :id,
               name: "episode_scheduling_episode_id_fkey",
               type: :uuid,
               prefix: "public"
             ),
             null: true

      remove :finalized_at
      remove :published_at
      remove :chosen_datetime
      remove :chosen_proposal_id
      remove :participant_persona_ids
      remove :owner_persona_id
      remove :status
    end

    execute "ALTER TABLE episode_scheduling ALTER COLUMN proposals DROP NOT NULL"
    execute "ALTER TABLE episode_scheduling ALTER COLUMN proposals DROP DEFAULT"

    execute "ALTER TABLE episode_scheduling ALTER COLUMN proposals TYPE jsonb USING CASE WHEN array_length(proposals, 1) > 0 THEN proposals[1] ELSE NULL END"
  end
end
