defmodule Radiator.Repo.Migrations.PersonaToUser do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    # Abandoned join table left over from an earlier (wrong) schema iteration.
    # It still carries an FK to `personas`, so it must be removed before the
    # `personas` table can be dropped.
    drop_if_exists table(:episode_personas)

    rename table(:episode_scheduling), :participant_persona_ids, to: :participant_user_ids

    rename table(:episode_scheduling), :owner_persona_id, to: :owner_user_id

    drop constraint(:episode_scheduling, "episode_scheduling_owner_persona_id_fkey")

    alter table(:episode_scheduling) do
      modify :owner_user_id,
             references(:users,
               column: :id,
               name: "episode_scheduling_owner_user_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :restrict
             )
    end

    drop constraint(:episode_participants, "episode_participants_persona_id_fkey")

    drop_if_exists unique_index(:episode_participants, [:episode_id, :persona_id],
                     name: "episode_participants_one_persona_per_episode_index"
                   )

    rename table(:episode_participants), :persona_id, to: :user_id

    create unique_index(:episode_participants, [:episode_id, :user_id],
             name: "episode_participants_one_user_per_episode_index"
           )

    alter table(:episode_participants) do
      modify :user_id,
             references(:users,
               column: :id,
               name: "episode_participants_user_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    # All FKs into `personas` have now been dropped, so the table can go.
    drop table(:personas)
  end

  def down do
    drop constraint(:episode_participants, "episode_participants_user_id_fkey")

    alter table(:episode_participants) do
      modify :user_id,
             references(:personas,
               column: :id,
               name: "episode_participants_persona_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    drop_if_exists unique_index(:episode_participants, [:episode_id, :user_id],
                     name: "episode_participants_one_user_per_episode_index"
                   )

    rename table(:episode_participants), :user_id, to: :persona_id

    create unique_index(:episode_participants, [:episode_id, :persona_id],
             name: "episode_participants_one_persona_per_episode_index"
           )

    drop constraint(:episode_scheduling, "episode_scheduling_owner_user_id_fkey")

    alter table(:episode_scheduling) do
      modify :owner_user_id,
             references(:personas,
               column: :id,
               name: "episode_scheduling_owner_persona_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :restrict
             )
    end

    rename table(:episode_scheduling), :owner_user_id, to: :owner_persona_id

    rename table(:episode_scheduling), :participant_user_ids, to: :participant_persona_ids

    # Rollback would require recreating the table manually
  end
end
