defmodule Radiator.Repo.Migrations.SchedulingForEpisodes do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:episode_scheduling, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :proposals, :map, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :episode_id,
          references(:episodes,
            column: :id,
            name: "episode_scheduling_episode_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    create unique_index(:episode_scheduling, [:episode_id],
             name: "episode_scheduling_unique_episode_index"
           )
  end

  def down do
    drop_if_exists unique_index(:episode_scheduling, [:episode_id],
                     name: "episode_scheduling_unique_episode_index"
                   )

    drop constraint(:episode_scheduling, "episode_scheduling_episode_id_fkey")

    drop table(:episode_scheduling)
  end
end
