defmodule Radiator.Repo.Migrations.AddPeopleDomain do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    rename table(:tracks), :episode_persona_id, to: :episode_participant_id

    drop constraint(:tracks, "tracks_episode_persona_id_fkey")

    create table(:episode_participants, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:tracks) do
      modify :episode_participant_id,
             references(:episode_participants,
               column: :id,
               name: "tracks_episode_participant_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:episode_participants) do
      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :episode_id,
          references(:episodes,
            column: :id,
            name: "episode_participants_episode_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :persona_id,
          references(:personas,
            column: :id,
            name: "episode_participants_persona_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :role_id,
          references(:roles,
            column: :id,
            name: "episode_participants_role_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    create unique_index(:episode_participants, [:episode_id, :persona_id],
             name: "episode_participants_one_persona_per_episode_index"
           )
  end

  def down do
    drop_if_exists unique_index(:episode_participants, [:episode_id, :persona_id],
                     name: "episode_participants_one_persona_per_episode_index"
                   )

    drop constraint(:episode_participants, "episode_participants_episode_id_fkey")

    drop constraint(:episode_participants, "episode_participants_persona_id_fkey")

    drop constraint(:episode_participants, "episode_participants_role_id_fkey")

    alter table(:episode_participants) do
      remove :role_id
      remove :persona_id
      remove :episode_id
      remove :updated_at
      remove :inserted_at
    end

    drop constraint(:tracks, "tracks_episode_participant_id_fkey")

    alter table(:tracks) do
      modify :episode_participant_id,
             references(:episode_personas,
               column: :id,
               name: "tracks_episode_persona_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    drop table(:episode_participants)

    rename table(:tracks), :episode_participant_id, to: :episode_persona_id
  end
end
