defmodule Radiator.Repo.Migrations.AddUserIdToPersonas do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:personas) do
      add :user_id,
          references(:users,
            column: :id,
            name: "personas_user_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nilify_all
          )
    end

    create unique_index(:personas, [:user_id], name: "personas_unique_user_index")
  end

  def down do
    drop constraint(:personas, "personas_user_id_fkey")

    drop_if_exists unique_index(:personas, [:user_id], name: "personas_unique_user_index")

    alter table(:personas) do
      remove :user_id
    end
  end
end
