defmodule Radiator.Repo.Migrations.AddWebauthnAuthStrategy do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:web_authn_credentials, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :credential_id, :binary, null: false
      add :sign_count, :bigint
      add :label, :text
      add :last_used_at, :utc_datetime_usec
      add :public_key, :binary, null: false

      add :user_id,
          references(:users,
            column: :id,
            name: "web_authn_credentials_user_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create unique_index(:web_authn_credentials, [:credential_id],
             name: "web_authn_credentials_unique_credential_id_index"
           )
  end

  def down do
    drop constraint(:web_authn_credentials, "web_authn_credentials_user_id_fkey")

    drop_if_exists unique_index(:web_authn_credentials, [:credential_id],
                     name: "web_authn_credentials_unique_credential_id_index"
                   )

    drop table(:web_authn_credentials)
  end
end
