defmodule Radiator.Repo.Migrations.UserFieldsAndPersonRemodel do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:users) do
      add :handle, :text
      add :avatar_url, :text

      add :person_id,
          references(:people,
            column: :id,
            name: "users_person_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    create unique_index(:users, [:handle], name: "users_unique_handle_index")

    alter table(:people) do
      remove :telephone
      remove :email
      remove :nickname
      remove :real_name
      add :first_name, :text, null: false, default: ""
      add :last_name, :text
      add :display_name, :text
      add :homepage_url, :text
      add :wikipedia_url, :text
      add :bio, :text
    end
  end

  def down do
    alter table(:people) do
      remove :bio
      remove :wikipedia_url
      remove :homepage_url
      remove :display_name
      remove :last_name
      remove :first_name
      add :real_name, :text, null: false
      add :nickname, :text
      add :email, :text
      add :telephone, :text
    end

    drop constraint(:users, "users_person_id_fkey")

    drop_if_exists unique_index(:users, [:handle], name: "users_unique_handle_index")

    alter table(:users) do
      remove :person_id
      remove :avatar_url
      remove :handle
    end
  end
end
